export default function Disclaimer() {
    return (
        <div className="disclaimer">
            <small className="disclaimer__text">These recipes are generated by an AI model, which may add ingredients to help ensure the result is flavorful and complete. While it strives to produce sensible and tasty recipes, please use your own discretion and culinary judgment when preparing or consuming any dish.</small>
        </div>
    )
}